# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2017, 5, 29, 13, 19, 30, 425109, tzinfo=utc), max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
