# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_user_guichet'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_namesender', models.CharField(max_length=50, verbose_name='Nom de l expediteur')),
                ('first_namesender', models.CharField(max_length=30, verbose_name='Prenom de l expediteur')),
                ('montant', models.IntegerField()),
                ('datedepot', models.DateTimeField(verbose_name='Date du  depot')),
                ('MTCN', models.CharField(max_length=50)),
                ('commission', models.IntegerField(verbose_name='Commission a payer')),
                ('last_namereceiver', models.CharField(max_length=50, verbose_name='Nom du  destinateur')),
                ('first_namereceiver', models.CharField(max_length=30, verbose_name='Prenom du destinateur')),
                ('cin', models.CharField(max_length=50, verbose_name='Carte nationale didentite')),
                ('datereceiver', models.DateTimeField(blank=True, null=True, verbose_name='Date de reception')),
                ('guichet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Guichet')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tarifs',
            new_name='Tarif',
        ),
        migrations.RemoveField(
            model_name='transferts',
            name='guichet',
        ),
        migrations.RemoveField(
            model_name='transferts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transferts',
        ),
        migrations.AddField(
            model_name='transfert',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.Tarif'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
