# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20170602_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='datereceiver',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de reception'),
        ),
    ]
