# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_auto_20170607_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='addressereceiver',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Adresse du destinataire'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='phonereceiver',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telephone du destinataire'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='villereceiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville   du  destinataire'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='villesender',
            field=models.CharField(default='BUJUMBURA', max_length=30, verbose_name="Ville de l' expediteur"),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='MTCN',
            field=models.CharField(default='Bonjour', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
